### ISSUE TITLE
第三方微信开放平台开发，调用createJsapiSignature方法时，报redis超时错误

### ISSUE THREAD

**Issue by anqilin1** [binarywang/weixin-java-mp-demo#109]
你好，第三方微信开放平台开发，调用createJsapiSignature方法时，会报redis超时错误，下面是错误信息，麻烦看一下可能是什么原因造成的
10:22:30.543 logback [http-nio-22081-exec-14] ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.RuntimeException: acquire timeouted] with root cause
java.lang.RuntimeException: acquire timeouted
  at me.chanjar.weixin.common.util.locks.JedisDistributedLock.lock(JedisDistributedLock.java:29)
  at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.getTicket(BaseWxMpServiceImpl.java:105)
  at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.getJsapiTicket(BaseWxMpServiceImpl.java:132)
  at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.createJsapiSignature(BaseWxMpServiceImpl.java:139)
  at cn.towee.beehive.weChat.controller.WxOpenApiController.createJsApiSignature(WxOpenApiController.java:89)
  at sun.reflect.GeneratedMethodAccessor172.invoke(Unknown Source)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

**Comment by binarywang** [comment]
acquire timeouted

这个看起来原因挺清楚的吧
